name: 'ROS 2 CI Action'
description: 'Run ROS 2 package test in CI using Github Actions.'
author: 'ROS Tooling Working Group'
branding:
  icon: 'activity'
  color: 'gray-dark'
inputs:
  colcon-mixin-name:
    default: ''
    description: 'Colcon mixin to be used to compile and test (empty means no mixin)'
    required: false
  colcon-mixin-repository:
    default: 'https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml'
    description: 'Mixin repository containing the mixin specified in colcon-mixin-name'
    required: false
  coverage-ignore-pattern:
    description: |
        Ignore all files matching this pattern in the coverage report.
        It will be injected in colcon-lcov-result --filter option.
        Useful for ignoring tests or examples in the coverage report.
  extra-cmake-args:
    default: ''
    description: |
        Additional flags passed to CMake (using colcon build --cmake-args)
    required: false
  colcon-extra-args:
    default: ''
    description: |
        Arbitrary space-separated additional flags to pass to colcon.
    required: false
  package-name:
    description: |
        Name of the package(s) under test, as expected by colcon.
        Passing multiple package names is allowed.
        Package names can be separated by any whitespace character.
    required: true
  source-ros-binary-installation:
    description: |
        Source setup.sh from one or more binary ROS installations (Linux only).
        For instance, if dashing is passed, /opt/ros/dashing/setup.sh will
        be sourced before running colcon.
        Multiple ROS distributions separated by one or more whitespace\
        characters are allowed. This is typically used to setup a ROS and
        a ROS 2 distribution to build packages relying on both, such as
        the ros1_bridge.
        Examples of valid values include "", "dashing", "melodic dashing".
    required: false
    default: ""
  vcs-repo-file-url:
    description: |
        repo file URL passed to vcs to initialize the colcon workspace.
        The URL may point to a local file, such as file://path/to/file.txt
    default: "https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos"
outputs:
  ros-workspace-directory-name:
    description: |
        root directory name of the ROS workspace created for this CI code.
runs:
  using: 'node12'
  main: 'dist/index.js'
