name: "ROS 2 CI Action"
description: "Run ROS 2 package test in CI using Github Actions."
author: "ROS Tooling Working Group"
branding:
  icon: "activity"
  color: "gray-dark"
inputs:
  colcon-defaults:
    default: ""
    description: |
      Valid JSON content to use as a colcon defaults.yaml file.
      Use a pipe to provide a multiline string.
      See: https://colcon.readthedocs.io/en/released/user/configuration.html#defaults-yaml
    required: false
  colcon-mixin-repository:
    default: "https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml"
    description: "Mixin repository containing the mixin(s) specified through colcon-defaults or colcon-extra-args"
    required: false
  coverage-ignore-pattern:
    default: ""
    description: |
      Ignore all files matching this pattern in the coverage report.
      It will be injected in colcon-lcov-result --filter option.
      Useful for ignoring tests or examples in the coverage report.
    required: false
  extra-cmake-args:
    default: ""
    description: |
      Additional flags passed to CMake (using colcon build --cmake-args)
    required: false
  colcon-extra-args:
    default: ""
    description: |
      Arbitrary space-separated additional flags to pass to colcon (build & test).
    required: false
  import-token:
    default: ""
    description: |
      GitHub personal access token (PAT) to use to import the repository.
      Useful if the repo is private.
      The PAT should have the "repo" scope.
    required: false
  package-name:
    description: |
      Limit the package(s) to be built and tested.
      If left empty this will build and test everything in the workspace - including packages from vcs-repo-file-url imports.
      Passing multiple package names is allowed.
      Package names can be separated by any whitespace character.
    required: false
    default: ""
  target-ros1-distro:
    description: |
      ROS 1 distribution to target for the build.  Will be used both for
      `rosdep install` and `source setup.bash`. Either or both of
      `target-ros1-distro` and `target-ros2-distro`, but at least one must
      be specified. Typically, both are specified when building packages
      that rely on both ROS versions, such as the ros1_bridge.
    required: false
  target-ros2-distro:
    description: |
      ROS 2 distribution to target for the build.  Will be used both for
      `rosdep install` and `source setup.bash`. Either or both of
      `target-ros1-distro` and `target-ros2-distro`, but at least one must
      be specified. Typically, both are specified when building packages
      that rely on both ROS versions, such as the ros1_bridge.
    required: false
  vcs-repo-file-url:
    description: |
      Repo file URL passed to vcs to initialize the colcon workspace.
      The URL may point to a local file, such as file://path/to/file.txt.
      For example, for ROS 2 Rolling source repositories, use:
      https://raw.githubusercontent.com/ros2/ros2/rolling/ros2.repos
    default: ""
  skip-tests:
    default: ""
    description: |
      Skip tests and code coverage data processing.
      Set to 'true'.
    required: false
  rosdep-skip-keys:
    default: ""
    description: |
      Keys to be skipped when installing dependencies via rosdep.
      Passing multiple keys is allowed.
      Keys names can be separated by any whitespace character.
    required: false
outputs:
  ros-workspace-directory-name:
    description: |
      root directory name of the ROS workspace created for this CI code.
runs:
  using: "node16"
  main: "dist/index.js"
