name: Auto approve

on:
  pull_request

jobs:
  # Auto-approve dependabot PRs since this repo requires at least one approving review.
  # Dependabot will automatically merge minor version upgrades
  # (see .dependabot/config.yml for more info).
  auto-approve-dependabot:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2.0.0
      if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
